[package]
name = "mutlijoueur-tetris"
version = "0.1.0"
authors = ["GALLAIS-POU Raphaël <raphael.gallaispou@reseau.eseo.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
